name: Sugerir uma melhoria
description: Uma ideia para o projeto
labels: ["enhancement"]
body:
  - type: textarea
    id: problema
    attributes:
      label: Que problema isso resolve
      description: Descreva a situação de uso, não a solução.
    validations:
      required: true

  - type: textarea
    id: proposta
    attributes:
      label: O que você propõe
    validations:
      required: true

  - type: textarea
    id: alternativas
    attributes:
      label: Alternativas consideradas
    validations:
      required: false
